version: "3"

# go-task Taskfile
# https://taskfile.dev

dotenv: [".env"]
silent: true

env:
  GOTOOLCHAIN:
    sh: awk '$1 == "go" { print "go" $2; exit }' go.mod

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run code linters"
    cmds:
      - go tool golangci-lint run -c .golangci.yml
      - go tool ifaceguard --config ifaceguard.cfg

  test:
    desc: "Run unit tests"
    cmds:
      - go test -race ./...

  itest:
    desc: "Run unit and integration tests"
    cmds:
      - go test -race -count=1 -tags=integration_tests ./...

  fix:
    desc: "Run go fix"
    cmds:
      - go fix ./...
      - go fmt ./...

  fmt:
    desc: "Format the codebase"
    cmds:
      - go fmt ./...
      - go tool golangci-lint fmt --config .golangci.yml ./...

  vet:
    desc: "Run go vet"
    cmds:
      - go vet ./...

  generate:
    desc: Generate code
    cmds:
      - go generate ./...

  build:
    desc: "Build the project"
    cmds:
      - go build -o bin/ ./cmd/classifier-mcp

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out -v
      - go tool cover -html=coverage.out -o coverage.html
