// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=classify
//

// Package classify is a generated GoMock package.
package classify

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/classifier-mcp/internal/domain"
	mo "github.com/samber/mo"
	gomock "go.uber.org/mock/gomock"
)

// MockIModel is a mock of IModel interface.
type MockIModel struct {
	ctrl     *gomock.Controller
	recorder *MockIModelMockRecorder
	isgomock struct{}
}

// MockIModelMockRecorder is the mock recorder for MockIModel.
type MockIModelMockRecorder struct {
	mock *MockIModel
}

// NewMockIModel creates a new mock instance.
func NewMockIModel(ctrl *gomock.Controller) *MockIModel {
	mock := &MockIModel{ctrl: ctrl}
	mock.recorder = &MockIModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIModel) EXPECT() *MockIModelMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockIModel) Evaluate(arg0 context.Context, arg1 Request) (Response, mo.Option[domain.Diagnostic]) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", arg0, arg1)
	ret0, _ := ret[0].(Response)
	ret1, _ := ret[1].(mo.Option[domain.Diagnostic])
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockIModelMockRecorder) Evaluate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockIModel)(nil).Evaluate), arg0, arg1)
}

// MockISourceReader is a mock of ISourceReader interface.
type MockISourceReader struct {
	ctrl     *gomock.Controller
	recorder *MockISourceReaderMockRecorder
	isgomock struct{}
}

// MockISourceReaderMockRecorder is the mock recorder for MockISourceReader.
type MockISourceReaderMockRecorder struct {
	mock *MockISourceReader
}

// NewMockISourceReader creates a new mock instance.
func NewMockISourceReader(ctrl *gomock.Controller) *MockISourceReader {
	mock := &MockISourceReader{ctrl: ctrl}
	mock.recorder = &MockISourceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISourceReader) EXPECT() *MockISourceReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockISourceReader) Read(arg0 context.Context, arg1 domain.FileSource) (AcquiredSource, mo.Option[domain.Diagnostic]) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(AcquiredSource)
	ret1, _ := ret[1].(mo.Option[domain.Diagnostic])
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockISourceReaderMockRecorder) Read(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockISourceReader)(nil).Read), arg0, arg1)
}
